### PR TITLE
Fix when applicationId ≠ package name

### PR DESCRIPTION
**Pull request by ncnlinh**
for using applicationIdSuffix in different flavors or when applicationId is different from package name in AndroidManifest #14

### CODE REVIEW

**Comment by fabriziomoscon** [comment]
This PR can be improved: https://github.com/ncnlinh/react-native-config/pull/3

**Comment by ncnlinh** [comment]
Thanks for the help @mehcode @fabriziomoscon

**Comment by fabriziomoscon** [comment]
I tested this on Android and for what I can see it works great. Please consider for merge

**Comment by mehcode** [comment]
Yep.. we're using it over here too :+1: (on android and iOS)

**Comment by pedro** [comment]
You folks rock! :+1: thanks so much, released in 0.0.7.

**Comment by ncnlinh** [comment]
Thank you @pedro, I've been using this lib since you introduced in in RN Meet-up SF. Amazing work!

**Comment by pedro** [comment]
wow, so glad to hear! :}

**Pull request merged**
